#!/usr/bin/env python3
import argparse
import json
import os
import shutil
import sys
import tarfile
from urllib.request import urlopen


def main(version, parent, dry_run):
    # https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#releases
    # No paging, assume no-one will install a really old version
    r = urlopen('https://api.github.com/repos/IDR/idr.openmicroscopy.org/releases')
    assert r.code == 200
    releases = json.load(r)

    if version == 'latest':
        release = releases[0]
    else:
        release = None
        for check in releases:
            if check['tag_name'] == version:
                release = check
                break
        if release is None:
            print('Failed to find release {}'.format(version))
            sys.exit(1)

    tag = release['tag_name']

    version_source_file = os.path.join(parent, 'VERSION')
    if not os.path.exists(version_source_file):
        print(f"Missing version file at {version_file}")

    dst = os.path.join(parent, tag)
    sym = os.path.join(parent, 'html')

    if os.path.exists(dst):
        print('{} already exists, not downloading'.format(dst))
    elif dry_run:
        print('Would download {}'.format(dst))
    else:
        www_assets = [a for a in release['assets'] if a['name'] == 'idr.openmicroscopy.org.tar.gz']
        assert len(www_assets) == 1, 'Expected one asset named idr.openmicroscopy.org.tar.gz'
        url = www_assets[0]['browser_download_url']

        h = urlopen(url)
        thetarfile = tarfile.open(fileobj=h, mode="r|gz")
        thetarfile.extractall(path=dst)
        h.close()
        print('Extracted {} to {}'.format(url, dst))
        
        version_dst_file = os.path.join(dst, "VERSION")
        shutil.copyfile(version_source_file, version_dst_file)
        print('Copied {} to {}'.format(version_source_file, version_dst_file))

    if os.path.exists(sym):
        assert os.path.islink(sym), '{} is not a symlink'.format(sym)
        target = os.readlink(sym)
        if target == dst:
            print('{} already points to {}, no changes made'.format(dst, sym))
            sys.exit(0)
        elif dry_run:
            print('Would remove symlink {} (target={})'.format(sym, target))
        else:
            print(target)
            # Mutator
            os.remove(sym)
    if dry_run:
        print('Would symlink {} to {}'.format(dst, sym))
        sys.exit(1)
    else:
        # Mutator
        os.symlink(dst, sym)
        print('Symlinked {} to {}'.format(dst, sym))
        sys.exit(0)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    xor = parser.add_mutually_exclusive_group()
    xor.add_argument('-n','--dry-run', action='store_true', default=True)
    xor.add_argument('-f','--force', action='store_false', dest="dry_run")
    parser.add_argument(
        '--parentdir', default='/srv/www/',
        help='Web-server directory for idr.openmicroscopy.org')
    parser.add_argument('--version', default='latest',
        help='Release to download')
    args = parser.parse_args()
    main(args.version, args.parentdir, args.dry_run)
